version: "3.8"
services:
    app-dev:
        build:
            context: .
            dockerfile: Dockerfile.dev
        ports:
            - "5174:5173"
        volumes:
            - .:/app
        env_file:
            - .env
        # environment:
        #   - NODE_ENV=development
    app-prod:
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - "5174:80"
        env_file:
            - .env.production
        # environment:
        #   - NODE_ENV=production
